name: instamusic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.17
  fancy_bottom_navigation_2: ^0.3.5
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  audio_video_progress_bar: ^2.0.3
  flutter_sequence_animation: ^4.0.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^15.2.9
  audio_service: ^0.18.18
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  iconsax: ^0.0.8
  fluttertoast: ^8.2.12
  flutter_svg: ^2.2.0
  carousel_slider: ^5.1.1
  bottom_navy_bar: ^6.1.0
  sliding_clipped_nav_bar: ^3.1.1
  photo_manager: ^3.7.1
  imagewidget: ^1.2.4
  disk_space_plus: ^0.2.5
  file_manager: ^1.0.2
  text_scroll: ^0.2.0
  flutter_colorpicker: ^1.1.0
  animations: ^2.0.11
  audioplayers: ^6.5.0
  page_transition: ^2.2.1
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  flutter_staggered_animations: ^1.1.1
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  sliding_up_panel: ^2.0.0+1
  provider: ^6.1.5
  marquee: ^2.3.0
  video_player: ^2.10.0
  path_provider: ^2.1.5
  audio_session: ^0.2.2
  flutter_tts: ^4.2.3
  device_info_plus: ^11.5.0
  android_content_provider: ^0.5.2
  audio_service_mpris: ^0.2.0
  just_audio_mpv: ^0.1.7
  flutter_portal: ^1.1.4
  video_thumbnail: ^0.5.6
  intl: ^0.20.2
  change_app_package_name: ^1.5.0
  smooth_page_indicator: ^1.2.1
  icons_plus: ^5.0.0
  flutter_localization: ^0.3.3
  on_audio_query_forked: ^2.9.1
  easy_audio: ^1.0.0
  badges: ^3.1.2
  floating: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appblue.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/images/background/
    - assets/images/svg/
    - assets/images/icons/
    - assets/customImages/
    - assets/fonts/
  fonts:
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf


